# -*- coding: utf-8 -*-
"""ComputerVision_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13CZDNQawemL0a6L_MZyhvL-FCGyu_3Fp
"""



"""Get the images from the internet


"""

!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IND-GPXX0XSBEN/lenna.png
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IND-GPXX0XSBEN/baboon.png
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IND-GPXX0XSBEN/driver.jpg

def get_concat_h(im1, im2):
    #https://note.nkmk.me/en/python-pillow-concat-images/
    dst = Image.new('RGB', (im1.width + im2.width, im1.height))
    dst.paste(im1, (0, 0))
    dst.paste(im2, (im1.width, 0))
    return dst

my_image = "lenna.png"

import os
cwd = os.getcwd()
cwd

image_path = os.path.join(cwd, my_image)
image_path

"""Load in Image using OpenCV"""

import cv2

image = cv2.imread(my_image)

image

type(image)

h, w, c = image.shape
print('height: ', h)
print('width:  ', w)
print('channel:', c)

image.max()

image.min()

"""# Plot an Image"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,10))
plt.imshow(image)
plt.show()

new_image=cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(10,10))
plt.imshow(new_image)
plt.show()

image = cv2.imread(image_path)
image.shape

cv2.imwrite("lenna.jpg", image)

"""# Gray Scale Images, Quantization and Color Channels"""

image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

image_gray.shape

import matplotlib.pyplot as plt
im = cv2.imread('driver.jpg')
im_gray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)

plt.figure(figsize=(10,10))
plt.imshow(im_gray,cmap='gray')
plt.show()

"""# Color channels"""

baboon=cv2.imread('baboon.png')
plt.figure(figsize=(10,10))
plt.imshow(cv2.cvtColor(baboon, cv2.COLOR_BGR2RGB))
plt.show()

baboon=cv2.imread('baboon.png')
plt.figure(figsize=(10,10))
plt.imshow(cv2.cvtColor(baboon, cv2.COLOR_BGR2RGB))
plt.show()

blue, green, red = baboon[:, :, 0], baboon[:, :, 1], baboon[:, :, 2]

im_bgr = cv2.vconcat([blue, green, red])

plt.figure(figsize=(10,10))
plt.subplot(121)
plt.imshow(cv2.cvtColor(baboon, cv2.COLOR_BGR2RGB))
plt.title("RGB image")
plt.subplot(122)
plt.imshow(im_bgr,cmap='gray')
plt.title("Different color channels  blue (top), green (middle), red (bottom)")
plt.show()

rows = 256

plt.figure(figsize=(10,10))
plt.imshow(new_image[0:rows,:,:])
plt.show()

columns = 256

plt.figure(figsize=(10,10))
plt.imshow(new_image[:,0:columns,:])
plt.show()

A = new_image.copy()
plt.imshow(A)
plt.show()

B = A
A[:,:,:] = 0
plt.imshow(B)
plt.show()

B = A
A[:,:,:] = 0
plt.imshow(B)
plt.show()

"""# Red channel to zero

"""

baboon_red = baboon.copy()
baboon_red[:, :, 0] = 0
baboon_red[:, :, 1] = 0
plt.figure(figsize=(10, 10))
plt.imshow(cv2.cvtColor(baboon_red, cv2.COLOR_BGR2RGB))
plt.show()

baboon_blue = baboon.copy()
baboon_blue[:, :, 1] = 0
baboon_blue[:, :, 2] = 0
plt.figure(figsize=(10, 10))
plt.imshow(cv2.cvtColor(baboon_blue, cv2.COLOR_BGR2RGB))
plt.show()

baboon_green = baboon.copy()
baboon_green[:, :, 0] = 0
baboon_green[:, :, 2] = 0
plt.figure(figsize=(10,10))
plt.imshow(cv2.cvtColor(baboon_green, cv2.COLOR_BGR2RGB))
plt.show()

image=cv2.imread('baboon.png')

image=cv2.imread('baboon.png')

image=cv2.imread('driver.jpg') # replace and add you image here name
baboon_blue=image.copy()
baboon_blue[:,:,1] = 0
baboon_blue[:,:,2] = 0
plt.figure(figsize=(10,10))
plt.imshow(cv2.cvtColor(baboon_blue, cv2.COLOR_BGR2RGB))
plt.show()

baboon_blue=cv2.imread('baboon.png')
baboon_blue=cv2.cvtColor(baboon_blue, cv2.COLOR_BGR2RGB)
baboon_blue[:,:,2] = 0
plt.figure(figsize=(10,10))
plt.imshow(baboon_blue)
plt.show()

baboon_g=cv2.imread('baboon.png')
baboon_g=cv2.cvtColor(baboon_g, cv2.COLOR_BGR2RGB)
baboon_g[:,:,1] = 0
plt.figure(figsize=(10,10))
plt.imshow(baboon_g)
plt.show()

baboon_r=cv2.imread('baboon.png')
baboon_r=cv2.cvtColor(baboon_r, cv2.COLOR_BGR2RGB)
baboon_r[:,:,0] = 0
plt.figure(figsize=(10,10))
plt.imshow(baboon_r)
plt.show()